title: Avenir Academia
author: Andrew Yu, et. al.
author_email: andrew@andrewyu.org
description: >-
  An attempt to bring free software to the masses. See the about page for more information.
  All content is under CC BY-SA, any version.
baseurl: ""
url: "https://aveniracademia.org"

theme: minima
plugins:
  - jekyll-feed

nav:
- title: About
  url: /about
