title: Avenir Academia
author: Andrew Yu, et. al.
author_email: andrew@andrewyu.org
description: >-
  An attempt to bring free software to the masses.
baseurl: ""
url: "https://aveniracademia.org"

theme: minima
plugins:
  - jekyll-feed

nav:
- title: About
  url: /about

# show_excerpts: true
